CREATE TABLE "history_orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"sorg" text,
	"bill_ty" text,
	"rev_type" text,
	"customer" text,
	"customer_name" text,
	"salesman" text,
	"item" text,
	"sloc" text,
	"plant" text,
	"material_no" text,
	"material_description" text,
	"size_dimen" text,
	"material_group" text,
	"mat_grp_desc" text,
	"mat_grp1" text,
	"mat_grp1_desc" text,
	"mat_grp2" text,
	"mat_grp2_desc" text,
	"mat_grp3" text,
	"mat_grp3_desc" text,
	"mat_grp4" text,
	"mat_grp4_desc" text,
	"mat_grp5" text,
	"mat_grp5_desc" text,
	"qty" double precision,
	"uom" text,
	"curr" text,
	"base_price" double precision,
	"intdept_price" double precision,
	"adjustment_price" double precision,
	"revenue_in_doc_curr" double precision,
	"revenue_in_loc_curr" double precision,
	"billing_no" text,
	"billing_date" text,
	"inco1" text,
	"inco2" text,
	"c" text,
	"cancelled" text,
	"delivery_no" text,
	"sales_order" text,
	"work_order" text,
	"po_no" text,
	"po_date" text,
	"po_type" text,
	"cost_of_sales" double precision,
	"profit_margin" double precision,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
